[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python scfs_api.py --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
